### ISSUE TITLE
For another animal species

### ISSUE THREAD

**Issue by EAST-J** [benjiebob/SMALify#16] opened 2020-10-31 11:15 UTC
Hi Ben,

Thanks a lot for your great  work. I would like to know what should I do if I want to use SMALify to another species(like horse). I see the SHAPE_FAMILY in config.py. I wonder anything else should I do?

**Comment by benjiebob** [comment] 2020-11-02 16:37
This *should* be everything you need to do! You'll need to edit your dataloader to load a horse sequence which has annotated 2D joints + segmentations but then it should work. Let me know how you get on, I'm grateful to have someone test this!

**Comment by EAST-J** [comment] 2020-11-03 13:57
Thanks, I would like to try in couple of days. Besides I see some other species annotations in data/BADJA/joint_annotations, I wonder there is images and segmentations?

**Comment by EAST-J** [comment] 2020-11-03 14:13
And I wonder is there any requirement for the size of the image

**Comment by Autumnfall-Me** [comment] 2020-11-18 09:32
hey ben,
Thanks a lot for your great work. I would like to build my new SMAL model such as pig. Now I have .OBJ 3D models, and have ran fitter_3d/optimise.py.  Then I got the npz file. If I save them as a pkl file, is it a SMAL model? I'm very confused. I would like to know what I should do next.

**Comment by benjiebob** [comment] 2020-12-15 12:27
BADJA does contain images + segs. I don't believe there is a requirement for the image size but let me know in a separate issue if you find problems for this. @Autumnfall-Me - your question seems a duplicate of https://github.com/benjiebob/SMALify/issues/18. 

Closing this issue for now, as I believe running the code on another SMAL animal category is working. Please reopen if you do find issues.

**Closed by benjiebob** 2020-12-15 12:27 UTC
